### ISSUE TITLE
Details About I-Former

### ISSUE THREAD

**Issue by Sun-Happy-YKX** [Szy-Young/ActFormer#3]
我对如何实现I-Former部分仍存有一些疑问。具体来说，按我的理解，特征向量在进行完PE后送入Transformer模块（先I-Former再T-Former），进行完PE后在代码层面应该是一个B*P*T*C的特征向量，经过rearrange后才能进行I-Former，然后再进行rearrange进行T-Former，由此循环往复。若想要达到如此效果，理应所有Batch内涵的P都应该一致，请问您在数据处理阶段是否是进行了Padding操作，将不足最大人数的数据（比如2~4人）全部Padding至最大人数数据（5人）。如若不是，烦请您能百忙之中帮我解一下惑！

**Comment by liangxuy** [comment]
对于不同的人数设定（2～5人），我们分别训练了不同的模型，详情见不同的gta combat config文件。

**Comment by Sun-Happy-YKX** [comment]
感谢您的回复，但是这么一来实质上2~5人各一个模型，请问一下他们之间是否有贡献的权重部分？（我的理解是完全独立的4各模型），如此一来，实质上需要保证不同人数尽可能分布相似，并且针对每个人数的数据量只有总数据量的1/4。
不知道我的理解是否有误，烦请您百忙之中帮忙解答一下，不胜感激！

**Comment by liangxuy** [comment]
2～5人各一个模型，没有权重贡献，都是从头训练。论文里给出了2～5人的数据量，分别是～2.3/1.9/1.5/1.2K，也可以下载处理好的数据文件查看详情。
