### ISSUE TITLE
About  for path in ['skt_txt/D0-30000', 'skt_txt/D30001-56880', 'skt_txt/s018_to_s032']:

### ISSUE THREAD

**Issue by Alicoo1907** [Szy-Young/ActFormer#5]
Hello,

I downloaded **NTU RGB+D 120** dataset and the **record about samples with missing skeletons**

1. and I put them in a common folder   "datasetntu120"    as 114,480 .skeleton file and 1 ntu_rgb120_missings.txt file

2. when i run code "python datasets/ntu120/prepare_ntu_data.py -s datasetntu12"

3. it says "FileNotFoundError: [WinError 3] The system cannot find the specified path: 'datasetntu120\\skt_txt/D0-30000'"

what change should I make in my datasetntu120 folder. I couldn't run the code

**Comment by Alicoo1907** [comment]
I don't understand what these 3 things are. 
'skt_txt/D0-30000' 
'skt_txt/D30001-56880' 
'skt_txt/s018_to_s032'

**Comment by liangxuy** [comment]
We split the whole 114,480 .skeleton files into three parts, i.e., D0-30000, D30001-56880 and s018_to_s032 to avoid downloading too large files. 
If you download all the skeleton files under the `./datasets/NTU120_RGBD/skeletons` folder, please refer to the [code modification](https://github.com/Szy-Young/ActFormer/blob/main/datasets/ntu120/prepare_ntu_data.py#L17-L18) here.
